title: Global Secure Access Setup Demos
description: Step-by-step guidance for Microsoft Entra GSA
remote_theme: just-the-docs/just-the-docs
search_enabled: true
aux_links:
  "Microsoft Learn: Global Secure Access": https://learn.microsoft.com/entra/global-secure-access/
